name: PlotGuardian
version: 1.5.4
author: mshax085
main: java.me.mshax085.guardian.PlotGuardian

commands:
  plot:
    description: The main command, use this to display all commands

permissions:
  plotguardian:
    build:
      interactAny:
        description: Allow a specific user to interact with any block despite restrictions
        default: op
      anywhere:
        description: Allow a specific user to build anywhere
        default: op
    diamondselector:
      description: Allow a specific user to use the diamond selector
      default: op
    blazerod:
      description: Allow a specific user to use the blazerod tool
      default: op
    create:
      description: Allow a specific user to create a plot
      default: op
    delete:
      description: Allow a specific user to delete a plot
      default: op
    clear:
      description: Allow a specific user to reset all values for a plot
      default: op
    sale:
      description: Allow a specific user to put a plot on/off sale
      default: op
    claim:
      description: Allow a specific user to claim a plot
      default: true
    declaim:
      description: Allow a specific user to declaim a plot
      default: true
    addmember:
      description: Allow a specific user to add a member
      default: true
    removemember:
      description: Allow a specific user to remove a member
      default: true
    silver:
      description: Allows for 3 plots
      default: true
    iron:
      description: Allows for 4 plots
      default: true
    gold:
      description: Allows for 5 plots
      default: true
    diamond:
      description: Allows for 6 plots
      default: true
    sorceror:
      description: Allows for 10 plots
      default: true
    wizard:
      description: Allows for 8 plots
      default: true
    moderator:
      description: Allows for 12 plots
      default: true
    list:
      description: Allow a specific user to his/her plots
      default: true